export const CREATE_EVENT = 'Make a new entry'
export const GET_ALL_EVENTS = 'Get all events'
export const SET_NEW_EVENT = 'Set the value of an event'
export const DELETE_EVENT = 'Delete an event'
export const GET_ONE_EVENT = 'Get a single event'
export const GET_RECENT_EVENTS = 'Gets last 50 events created'
export const UPDATE_EVENT = 'Updates an event'
